export const texts = {
    "ENG": {
        "MANAGE_CAMPAIGN": "Manage Campaigns",
        "UPCOMING": "Upcoming Campaigns",
        "LIVE": "Live Campaigns",
        "PAST": "Past Campaigns",
        "DATE": "DATE",
        "CAMPAIGN": "CAMPAIGN",
        "VIEW": "VIEW",
        "ACTIONS": "ACTIONS",
        "DAYS": "Days",
        "AHEAD": "Ahead",
        "TODAY": "Today",
        "AGO": "Ago",
        "VIEW_PRICING": "View Pricing",
        "CSV": "CSV",
        "REPORT":"Report",
        "SCHEDULE_AGAIN":"Schedule Again",
        "PRICING":"Pricing",
        "CLOSE": "Close",
        "SWITCH": "Switch To German"
    },
    "GER": {
        "MANAGE_CAMPAIGN": "Kampagnen verwalten",
        "UPCOMING": "Kommende Kampagne",
        "LIVE": "Live-Kampagne",
        "PAST": "Vergangene Kampagnen",
        "DATE": "DATUM",
        "CAMPAIGN": "KAMPAGNE",
        "VIEW": "AUSSICHT",
        "ACTIONS": "AKTIONEN",
        "DAYS": "Tage",
        "AHEAD": "Voraus",
        "AGO": "Vor",
        "TODAY": "Heute",
        "VIEW_PRICING": "Preise anzeigen",
        "CSV": "CSV",
        "REPORT":"BERICHT",
        "SCHEDULE_AGAIN":"Planen Sie erneut",
        "PRICING":"Preisgestaltung",
        "CLOSE": "Schließen",
        "SWITCH": "Switch To English"
    }
}